' Пример описания диаграммы. Удалить перед началом работы.

@startuml {ProjectName}-entities

entity "Entity Name" as EntityName {
    attributeFirst : type
    attributeSecond : type
}

entity "Other Entity Name" as OtherEntityName {
    attributeFirst : type
    attributeSecond : type
}

enum EnumerationName {
    FIRST
    SECOND
    OTHER_ITEM
}

EntityName ..> EnumerationName
EntityName "1" -- "*" OtherEntityName

@enduml