' Пример описания диаграммы. Удалить перед началом работы.

@startuml {ProjectName}-sequences-{CaseName}

actor "Mister Bob" as Bob
participant "Miss Alice" as Alice

Bob -> Alice : hello
activate Alice

Alice -> Alice : some action

return bye

@enduml