@startuml {ProjectName}-sequences-{CaseName}

Bob -> Alice : hello
activate Alice

Alice -> Alice : some action

return bye

@enduml



@startuml {ProjectName}-sequences-{OtherCaseName}

participant User

User -> A: DoWork
activate A

A -> B: << createRequest >>
activate B

B -> C: DoWork
activate C

return WorkDone

B --> A: RequestCreated
deactivate B

A -> User: Done
destroy A

@enduml