' Пример описания диаграммы. Удалить перед началом работы.

@startuml {ProjectName}-sequences-{EntityName}-{StateName}

hide empty description

[*] --> State1

State1 --> [*]: this is a string

State1 : entry: this is a string
State1 : exit: this is another string

State1 --> State2: this is a string

State2 --> [*]: this is a string

@enduml